Sommelier 9
microservices-course-itmo/sommelier pull request #19
Opened 2020-10-26 16:43 UTC by maxpavlov9991

something like switch

2020-10-26 18:23 UTC, StanislavMyakishev requested changes

2020-10-26 18:23 UTC, StanislavMyakishev commented on App/components/Switch/switch.tsx
> +  type = 'heart',
Please consider adding a theme prop like "switchType" to it won't be hardcoded

2020-10-26 18:23 UTC, StanislavMyakishev commented on App/components/Switch/switch.tsx
> +  onChange = (): void => {},
Do we rly need default empty functions

2020-10-26 18:23 UTC, StanislavMyakishev commented on App/components/Switch/switch.types.ts
> +export type Props = {
Maybe it makes sense to move this type to /switch.tsx?

2020-10-26 18:23 UTC, StanislavMyakishev commented on App/components/Switch/switch.tsx
> +  useEffect(() => {
Maybe we should use toggle function like 
```javascript
const toggleSwitch = () => disabled && setValue(!value);
```

2020-10-26 18:23 UTC, StanislavMyakishev commented on App/components/Switch/switch.tsx
> +  onChange = (): void => {},
If we will change the logic of value consider renaming onChange -> setValue

2020-10-26 18:23 UTC, StanislavMyakishev commented on App/components/Switch/switch.tsx
> +      {(() => {
Please refer to the Typography component so it would be the same usage

2020-10-26 18:23 UTC, StanislavMyakishev commented on App/components/Switch/switch.styled.ts
> +  ${({ disabled }) => (disabled ? `opacity: 0.5;` : ``)}
Use && or ?? instead of ? : operator

2020-11-02 11:01 UTC, maxpavlov9991 commented on App/components/Switch/switch.tsx
> +  onChange = (): void => {},
да

2020-11-02 11:21 UTC, maxpavlov9991 commented on App/components/Switch/switch.types.ts
> +export type Props = {
мэйби

2020-11-02 11:56 UTC, maxpavlov9991 commented on App/components/Switch/switch.types.ts
> +export type Props = {
хотя не, получается зацикленность при импорте его в styled

2020-11-03 15:15 UTC, StanislavMyakishev approved these changes

2020-11-03 15:16 UTC, merged